### PR TITLE
Simple changes, but missing license

### PR DESCRIPTION
**Pull request by plandes**
Hi John,

Looks like we're in some of the same circles (JDEE and ML).  I'd like to fork your repo and add some add the compiled jars to maven central.  However, they need a license and you haven't specified any.  I'll need to (probably) use the same license as you (and would be willing).

Will you please specify a license (regardless if you accept these changes or not).

Thanks very much.

Regards,
Paul Landes

### CODE REVIEW

**Comment by jconwell** [comment]
Hi Paul,
Glad the library was useful (though probably a bit out of date).  I'll get
a license file added to the repo.  I'm guessing Apache 2.0, but its been a
while since I thought about software licenses and want to read up a bit.
It might happen tonight/tomorrow, otherwise not until late next week.  Work
is gonna get busy over the weekend so I wont have time until then.

On Tue, Jul 5, 2016 at 2:05 PM, Paul Landes notifications@github.com
wrote:

> Hi John,
> 
> Looks like we're in some of the same circles (JDEE and ML). I'd like to
> fork your repo and add some add the compiled jars to maven central.
> However, they need a license and you haven't specified any. I'll need to
> (probably) use the same license as you (and would be willing).
> 
> Will you please specify a license (regardless if you accept these changes
> or not).
> 
> Thanks very much.
> 
> Regards,
> 
> ## Paul Landes
> 
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/jconwell/coreNlp/pull/2
> Commit Summary
> - initial add
> - upgrade to current used stanford deps
> - java standard package
> 
> File Changes
> - _M_ pom.xml https://github.com/jconwell/coreNlp/pull/2/files#diff-0
>   (6)
> - _R_ src/main/java/intoxicant/analytics/corenlp/NlpOptions.java
>   https://github.com/jconwell/coreNlp/pull/2/files#diff-1 (4)
> - _R_ src/main/java/intoxicant/analytics/corenlp/StopwordAnnotator.java
>   https://github.com/jconwell/coreNlp/pull/2/files#diff-2 (11)
> - _R_ src/test/java/intoxicant/analytics/corenlp/NlpOptionsTest.java
>   https://github.com/jconwell/coreNlp/pull/2/files#diff-3 (0)
> - _R_
>   src/test/java/intoxicant/analytics/corenlp/StopwordAnnotatorTest.java
>   https://github.com/jconwell/coreNlp/pull/2/files#diff-4 (12)
> 
> Patch Links:
> - https://github.com/jconwell/coreNlp/pull/2.patch
> - https://github.com/jconwell/coreNlp/pull/2.diff
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/jconwell/coreNlp/pull/2, or mute the thread
> https://github.com/notifications/unsubscribe/AAf0Xb2I69uBkhwtVyUzGI5v8gWy3sz_ks5qSscZgaJpZM4JFiBm
> .

## 

Thanks,
John C

**Comment by plandes** [comment]
I'm more and more moving to OSS (and the apache license is good) myself.  I believe there's some new clause in the new GPL that even "spreads" to services running software that carries the license, but I don't know the details.

Also, do you mind me "repackaging" it with just the stopword annotator?  That's what I am using it for and didn't put any time in updating the other class.

Thanks.

**Comment by plandes** [comment]
Hi John,

I've gone ahead and added the Apache 2.0 license to my repository and I'll keep the fork separate since I've removed some of your code (I only need and want to use the stopword annotator).

I'll change the license to whatever you use once you get the time to look into and commit to your repo.

Here's my forked repo:

https://github.com/plandes/stopword-annotator

Please take a look and give me your thoughts.

Thanks.

**Comment by jconwell** [comment]
Hey Paul,
Sorry it took so long.  Was out of town.  I've added the Apache 2.0 license to my repo as well.  Glad you found the code useful!

**Comment by plandes** [comment]
No problem, I just appreciate the response and making this easy.  Cheers!

**Pull request closed without merging**
